{
    "command.error.internal": "Error interno al intentar procesar este comando. {error}"
}